channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.8.2
- pytorch=1.6.0
- torchvision=0.7.0
- torchtext==0.7.0
- pytorch-lightning==1.0.2
- pip
- pip:
  - mlflow
  - sklearn
  - cloudpickle==1.6.0
  - boto3
  - transformers>=4.0.0
  - pandas
